### PR TITLE
Embed pages

### PR DESCRIPTION
**Pull request by pablopareja**
### Embed project card
Parameters:

- `embed=true`
- `embedType=project-card`
- `id=xxx`

Example: https://reforestation.app?sort=Context&country=All&filters=%5B%5D&embed=true&embedType=project-card&id=24

image

### Embed project list
Parameters:

- `embed=true`
- `embedType=project-list`

Example: https://reforestation.app?sort=Context&country=All&filters=%5B%5D&embed=true&embedType=project-list

image

### Embed filters
Parameters:

- `embed=true`
- `embedType=filters`

Example: https://reforestation.app?sort=Context&country=All&filters=%5B%5D&embed=true&embedType=filters

image

### CODE REVIEW

**Comment by WillieShubert** [comment]
Hey @pablopareja , 

I tried to embed the filters and the project list using the example URLs and it provided the whole page rather than just the portion included the examples you shared in the local version. See the attached screenshot with what I am seeing here: 

Screen Shot 2021-05-11 at 6 44 34 PM

**Comment by pablopareja** [comment]
Hi @WillieShubert,
Thanks for reporting this, it should be fixed now.
Could you confirm that you're able to create the different embeds when you have a minute?
Thanks in advance!

**Comment by WillieShubert** [comment]
Hi @pablopareja , I am testing it and have been successful with the filters. Thanks for taking care of this.

**Comment by WillieShubert** [comment]
Hey @clementprdhomme  and @develaper , is it possible to update this page so that we can have some documentation about how to use the embed functionality? The currently used embeds are all broken.

**Pull request merged**
